name: BCODMO-KG-data
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.5
  - bokeh=2.0.1
  - boost-cpp=1.72.0
  - bqplot=0.12.12
  - branca=0.3.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cryptography=2.9.2
  - curl=7.69.1
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fiona=1.8.13
  - folium=0.11.0
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=3.0.4
  - geopandas=0.7.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.64.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - hdf4=4.2.13
  - hdf5=1.10.6
  - holoviews=1.13.2
  - html5lib=1.0.1
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.6.1
  - importlib_metadata=1.6.1
  - ipykernel=5.3.0
  - ipyleaflet=0.13.1
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isodate=0.6.0
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9d
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - kealib=1.4.13
  - keepalive=0.5
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.69.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgdal=3.0.4
  - libgfortran-ng=7.5.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=10.0.0
  - lxml=4.5.1
  - lz4-c=1.9.2
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - munch=2.5.0
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.5
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - panel=0.9.5
  - param=1.9.3
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.1.1
  - pixman=0.38.0
  - plotly=4.8.1
  - poppler=0.87.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyviz_comms=0.7.5
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qt=5.12.5
  - rdflib=5.0.0
  - readline=8.0
  - requests=2.23.0
  - retrying=1.3.3
  - rtree=0.9.4
  - send2trash=1.5.0
  - setuptools=47.1.1
  - shapely=1.7.0
  - six=1.15.0
  - sparqlwrapper=1.8.5
  - sqlite=3.30.1
  - tbb=2020.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.7.7
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.46.1
  - traitlets=4.3.3
  - traittypes=0.2.1
  - typing_extensions=3.7.4.2
  - tzcode=2020a
  - urllib3=1.25.9
  - wcwidth=0.2.4
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - ipyiframe==0.1.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1

